# Generated by Django 4.2.4 on 2023-08-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='Email_id',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='First_name',
            new_name='Employee_Name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='user_name',
        ),
        migrations.AddField(
            model_name='register',
            name='Company_Name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='Designation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
