# Generated by Django 4.2.4 on 2023-08-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_log'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='log',
            new_name='login',
        ),
    ]
