# Generated by Django 4.2.4 on 2023-08-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='audii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=20)),
                ('audio', models.FileField(upload_to='djangoapp/static')),
                ('vname', models.CharField(max_length=20)),
                ('video', models.FileField(upload_to='djangoapp/static')),
                ('pname', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='djangoapp/static')),
            ],
        ),
    ]
