# Generated by Django 4.2.4 on 2023-10-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_filemodel_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileuploads_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfname', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='pdf/')),
                ('audioname', models.CharField(max_length=30)),
                ('audio', models.FileField(upload_to='audio/')),
                ('videoname', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='video/')),
            ],
        ),
    ]
