from django.urls import path
from .views import *
urlpatterns=[
    path('first/',first),
    path('second/',second),
    path('third/',third),
    path('work/',work),
    path('index/',index),
    path('registration/',reg),
    path('employee/',emp),
    path('login/',login),
    path('upload/',upload),
    path('audios/',audi),
    path('state/',state),
    path('display/',display),
    path('filedisplay/',filedisplay),
    path('update_data/<int:id>',update_data),
    # path['update_employee/',update_employee],
    path('delete/<int:id>',delete),
    path('authuserreg/',userregistration),
    path('userlog/',cust_login),
    path('disp/',UserListView.as_view(),name='disp'),
    # path('register/', register.as_view(),name='register' ),
    # path('login1/',login1.as_view(),name='login1'),
    # path('userreg/',userregister.as_view(),name='userreg'),
    path('aulogin/',user_login.as_view(),name='user_login'),
    path('userreg/',userregister.as_view(),name='userreg'),
    path('login2/',loginnew1.as_view(),name='login2'),
    path('del/<pk>',re.as_view(),name='del'),   #pk=primary key
    path('detail/<pk>',detail.as_view(),name='detail'),
    path('up/<pk>',up.as_view(),name='up'),
    path('imageupload/',image_upload.as_view(),name='imageupload'),
    path('imagedisplay/',image_list.as_view(),name='imagedisplay'),
    path('imagedelete/<pk>',image_delete.as_view(),name='delete'),
    path('imagedetail/<pk>',image_detail.as_view(),name='details'),
    path('imageupdate/<pk>',image_update.as_view(),name='update'),
    path('fileupload/',fileclass.as_view(),name='fileupload'),
    path('display_file/',display_file.as_view(),name='display_file'),
    path('deletefile/<pk>',deletefile.as_view(),name='deletefile'),
    path('detailfile/<pk>',detailfile.as_view(),name='detailfile'),
    path('update_file/<pk>',updatefile.as_view(),name='update_file'),

]
